aarthus/artwork/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from aarthus.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)


class Artwork(SurrogatePK, db.Model):
    __tablename__ = 'artwork'

    name = Column(db.String(80), unique=True, nullable=False)
    artist = Column(db.String(80), unique=False, nullable=False)
    year = Column(db.String(4), unique=False, nullable=True)
    type = Column(db.String(80), unique=False, nullable=True)
    attributed = Column(db.Boolean, unique=False, nullable=False, default=False)
    size1 = Column(db.Integer, unique=False, nullable=True)
    size2 = Column(db.Integer, unique=False, nullable=True)
    size3 = Column(db.Integer, unique=False, nullable=True)
    color = Column(db.String(7), unique=False, nullable=True)
    image = Column(db.String(255), unique=False, nullable=True)

    description = Column(db.Text, unique=False, nullable=True)
    literature = Column(db.Text, unique=False, nullable=True)

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Artwork({name})>'.format(name=self.name)

aarthus/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template
from aarthus.settings import ProdConfig
from aarthus.assets import assets
from aarthus.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar,
    api_manager,
)
from aarthus import main, artwork

UPLOAD_FOLDER = '/tmp/uploads'

def create_app(config_object=ProdConfig):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    api_manager.init_app(app, flask_sqlalchemy_db=db)
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    return None


def register_blueprints(app):
    app.register_blueprint(main.views.blueprint)
    app.register_blueprint(artwork.views.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

aarthus/artwork/__init__.py
from . import views

aarthus/artwork/views.py
# -*- coding: utf-8 -*-
import os

from flask import Blueprint, request, render_template, url_for, redirect, send_from_directory
from werkzeug.utils import secure_filename


blueprint = Blueprint('artwork', __name__, static_folder="../static")

@blueprint.route('/artwork/')
def list():
    return render_template("artwork/list.html")

@blueprint.route('/upload', methods=['POST'])
def upload_file():
    file = request.files['file']
    if file:
        filename = secure_filename(request.form['flowIdentifier'])
        # XXX Get UPLOAD folder from config
        file.save(os.path.join('/tmp/', filename))
        return redirect(url_for('artwork.uploaded_file',
                                filename=filename))

@blueprint.route('/uploads/<filename>')
def uploaded_file(filename):
    # XXX Get UPLOAD folder from config
    return send_from_directory('/tmp/',
                               filename)

aarthus/main/__init__.py
from . import views

aarthus/main/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, url_for, redirect, render_template

blueprint = Blueprint('main', __name__, static_folder="../static")

@blueprint.route('/')
def home():
    return redirect(url_for('artwork.list'))

@blueprint.route('/about/')
def about():
    return render_template("main/about.html")

aarthus/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('main.home')}}">log in</a> or
            <a href="{{ url_for('main.home') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

aarthus/templates/artwork/list.html
{% extends "layout.html" %}
{% set active_page = "artwork" %}
{% set angular_app = "artwork" %}

<!-- XXX should be done with flask assets -->
{% block js %}
<script type="text/javascript" src="/static/js/artwork.js"></script>
{% endblock %}

{% block content %}
{% raw %}
<div ng-controller="IndexCtrl" ng-cloack>
    <div class="container-fluid">
        <div class="row" style="margin-top: 30px">
            <div class="col-lg-4">
                <h1 style="margin-top: -12px; padding-bottom: 20px">Inventory</h1>
            </div>
            <div class="col-lg-4">
                <input
                        type="text"
                        class="form-control"
                        id="search"
                        placeholder="Search your {{ artworks.length }} artworks"
                        ng-model="search_text">
            </div>
            <div class="col-lg-4">
            </div>
        </div>
    </div>
     <div class="container-fluid">
       <script type="text/ng-template" id="deleteArtwork.html">
            <div class="modal-header">
                <h3 class="modal-title">Deleting Artworks</h3>
            </div>
            <div class="modal-body">
                <ul>
                    <li ng-repeat="artwork in artworks_to_delete">
                        {{ artwork.name }}, {{ artwork.artist }} ({{ artwork.year }})
                    </li>
                </ul>
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" ng-click="ok()">Delete</button>
                <button class="btn btn-primary" ng-click="cancel()">Cancel</button>
            </div>
        </script>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <div class="row">
                                <div class="col-lg-offset-2 col-lg-3">
                                    <h5>Title &amp; Date</h5>
                                </div>
                                <div class="col-lg-2">
                                    <h5>Medium &amp; Material</h5>
                                </div>
                                <div class="col-lg-2">
                                    <h5>Dimensions &amp; Color</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body" ng-repeat="artwork in artworks | filter:search_text">
                        <form editable-form shown="inserted == artwork" name="editableForm" onaftersave="save(artwork)">
                        <div class="row">
                            <div class="col-lg-2"
                                 flow-init
                                 flow-files-submitted="$flow.upload()"
                                 flow-file-success="artwork.image = $flow.files[0].uniqueIdentifier">
                                <img
                                        class=""
                                        height="150"
                                        ng-src="/uploads/{{ artwork.image }}"
                                        flow-img="$flow.files[0]">
                                <div ng-show="editableForm.$visible">
                                    <button
                                            type="button"
                                            class="btn btn-primary"
                                            flow-btn>
                                        <span class="glyphicon glyphicon-file"></span> Upload picture</button>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <h4 class="product-name">
                                    <strong editable-text="artwork.name">{{ artwork.name || "empty" }}</strong>
                                </h4>
                                <h4>
                                    <small editable-text="artwork.artist">{{ artwork.artist || "empty" }}</small>
                                </h4>
                                <h4>
                                    <small editable-text="artwork.year">{{ artwork.year || "empty" }}</small>
                                </h4>
                            </div>
                            <div class="col-lg-2">
                                <h4>
                                    <strong
                                            editable-select="artwork.type"
                                            e-ng-options="t.value as t.text for t in types"
                                            e-ng-change="artwork.type = $data">
                                    {{ artwork.type }}
                                    </strong>
                                </h4>
                            </div>
                            <div class="col-lg-2">
                                <h4>
                                    <strong>
                                        <span editable-text="artwork.size1" e-style="width: 50px">{{ artwork.size1 }}</span>
                                        {{ artwork.type == 'sculpture' ? 'X' : ':' }}
                                        <span editable-text="artwork.size2" e-style="width: 50px">{{ artwork.size2 }}</span>
                                        {{ artwork.type == 'sculpture' ? 'X' : ':' }}
                                        <span editable-text="artwork.size3" e-style="width: 50px">{{ artwork.size3 }}</span>
                                        {{ artwork.type == 'sculpture' ? 'cm' : '' }}
                                    </strong>
                                </h4>
                                <h3>
                                    <span
                                            class="label label-default"
                                            editable-color="artwork.color"
                                            style="background-color: {{ artwork.color }}"
                                            e-style="width: 100px; height: 40px">
                                        {{ artwork.color }}</span>
                                </h3>
                            </div>
                            <div class="col-lg-3 text-right">
                                <button
                                        type="submit" class="btn btn-primary btn-sm"
                                        ng-click="editableForm.$show()"
                                        ng-show="editableForm.$visible"
                                        ng-disabled="editableForm.$waiting">
                                    <span class="glyphicon glyphicon-ok"></span>&nbsp;Save
                                </button>
                                <button
                                        type="button" class="btn btn-default btn-sm"
                                        ng-click="editableForm.$show()" ng-show="!editableForm.$visible">
                                    <span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit
                                </button>
                                <button
                                        type="button" class="btn btn-default btn-sm"
                                        ng-click="delete(artwork)">
                                    <span class="glyphicon glyphicon-trash"></span>&nbsp;Delete
                                </button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-offset-2 col-lg-8">
                               <div class="row">
                                    <span editable-checkbox="artwork.attributed" e-title="Artwork only attributed to this artist?">
                                    <span
                                            class="glyphicon"
                                            ng-class="{'glyphicon-ok text-success': artwork.attributed, 'glyphicon-remove text-danger': !artwork.attributed}"></span>&nbsp;
                                    {{ artwork.attributed && "This artwork is only attributed to the artist" || "This artwork is attributed to multiple artists" }}
                                    </span>
                               </div>
                               <div class="row" style="margin-top: 20px">
                                   <div class="col-lg-4">
                                       <pre
                                               ng-show="artwork.description"
                                               editable-textarea="artwork.description"
                                               e-rows="7"
                                               e-cols="60">{{ artwork.description }}</pre>
                                   </div>
                                   <div class="col-lg-4">
                                       <pre
                                               ng-show="artwork.literature"
                                               editable-textarea="artwork.literature"
                                               e-rows="7"
                                               e-cols="60">{{ artwork.literature }}</pre>
                                   </div>
                               </div>
                            </div>
                        </div>
                        </form>
                        <hr>
                    </div>
                    <div class="panel-footer">
                        <div class="row text-center">
                            <div class="col-lg-12">
                                <button
                                        type="button" href="" class="btn btn-default pull-right"
                                        ng-click="new()">
                                    <span class="glyphicon glyphicon-plus-sign"></span>&nbsp;Add Artwork
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endraw %}
{% endblock %}

aarthus/templates/footer.html
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <footer>
                <small>
                    &copy; 2014 - Remco Wendt

                    <ul class="footer-nav">

                        <li><a href="{{ url_for('main.about') }}">About</a></li>

                        <li><a href="mailto:remco.wendt@gmail.com">Contact</a></li>
                    </ul>
                </small>
            </footer>
        </div>
    </div>
</div>

aarthus/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    Aarthus
  
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}"{% if angular_app %} ng-app="{{ angular_app }}" {% endif %}>
{% block body %}
{% set active_page = active_page|default('index') %}
{% include "nav.html" %}

<header>{% block header %}{% endblock %}</header>
<div class="container-fluid">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

  </div>

</div><!-- end container -->

{% block content %}{% endblock %}

{% include "footer.html" %}
<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

aarthus/templates/main/about.html
{% extends "layout.html" %}

{% block content %}
<div class="body-content">
    <div class="row">
      <h1>About</h1>
      <p>This is just an exampe app to show my skills</p>
    </div>
</div>
{% endblock %}

aarthus/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a>Cockpit</a></li>
      <li><a>Gagosian Gallery</a></li>
      <li><a>Artists</a></li>
      <li{% if active_page == 'artwork' %} class="active"{% endif %}><a href="{{ url_for('artwork.list') }}">Artworks</a></li>
      <li><a>Shows</a></li>
    </ul>
    {% if current_user and current_user.is_authenticated() %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a></p>
        </li>
        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

    </ul>
    {% elif form %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{ url_for('public.register') }}">Create account</a></li>
    </ul>
    <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username(placeholder="Username", class_="form-control") }}
        {{ form.password(placeholder="Password", class_="form-control") }}
      </div>
      <button type="submit" class="btn btn-default">Log in</button>
    </form>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>